import Navigationbar from "@/components/Navigationbar";
import { ReactNode } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigationbar/>
        <main>
        {children}
        </main>
      </body>
    </html>
  );
}
